# Generated by Django 4.2.1 on 2023-05-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/static/images/placeholder.png', upload_to='categories/'),
        ),
    ]
